---
# Игнорировать определенные правила (при необходимости)
# DL3008 — разрешаем apt-get install без фиксации версий пакетов (опционально для учебных целей)
ignored:
  - DL3008

# Жестко требовать фиксацию версий базовых образов (запрет :latest)
# Пример: ubuntu:24.04 или alpine:3.20
trustedRegistries:
  - docker.io
  - ghcr.io

# Контроль разрядности и форматов команд
severity:
  DL3000: error # Ошибка валидации структуры Dockerfile
  DL3002: error # Запрет переключения на root пользователя в конце сборки
  DL3006: warning # Базовый образ не имеет явного тега версии
  DL3020: error # Использовать COPY вместо ADD
